name: Print Token Request URL

on: [push]

jobs:
  print-url:
    runs-on: ubuntu-latest
    steps:
    - name: Print Token Request URL
      run: echo "The token request URL is: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}"
